import { AppError } from '../errors.js';

const notImplemented = async () => {
  throw new AppError('config', 'Supabase adapter not implemented yet');
};

export const listCategories = notImplemented;
export const getCategory = notImplemented;
export const searchBusinesses = notImplemented;
export const searchProducts = notImplemented;
export const getBusinessBySlug = notImplemented;
export const getProductById = notImplemented;
export const listReviews = notImplemented;
export const getMyReview = notImplemented;
export const saveMyReview = notImplemented;
export const deleteMyReview = notImplemented;
export const getSession = notImplemented;
export const onAuthChange = notImplemented;
export const signUp = notImplemented;
export const signIn = notImplemented;
export const signOut = notImplemented;
export const sendPasswordReset = notImplemented;
export const updatePassword = notImplemented;
export const getMe = notImplemented;
export const updateMe = notImplemented;
export const uploadAvatar = notImplemented;
export const revealContact = notImplemented;
export const getSavedIds = notImplemented;
export const listSavedBusinesses = notImplemented;
export const listSavedProducts = notImplemented;
export const setSaved = notImplemented;
export const trackView = notImplemented;
export const listRecent = notImplemented;
export const listConnected = notImplemented;
export const becomeSeller = notImplemented;
export const getMyBusiness = notImplemented;
export const saveMyBusiness = notImplemented;
export const saveMyContacts = notImplemented;
export const uploadBusinessImage = notImplemented;
export const removeBusinessImage = notImplemented;
export const listMyProducts = notImplemented;
export const saveProduct = notImplemented;
export const deleteProduct = notImplemented;
export const uploadProductImage = notImplemented;
export const removeProductImage = notImplemented;
export const addVideo = notImplemented;
export const removeVideo = notImplemented;
export const getSubmitChecklist = notImplemented;
export const submitForReview = notImplemented;
export const setAvailableToday = notImplemented;
export const getMyStats = notImplemented;
export const listApplications = notImplemented;
export const getApplication = notImplemented;
export const decideApplication = notImplemented;
export const sendEnquiry = notImplemented;
export const findMyThread = notImplemented;
export const listMyThreads = notImplemented;
export const getThread = notImplemented;
export const sendMessage = notImplemented;
export const markThreadRead = notImplemented;
export const listNotifications = notImplemented;
export const markNotificationsRead = notImplemented;
export const getUnreadCounts = notImplemented;
